### PR TITLE
Added main tag in package.json file that is breaking webpack compilation

### PR DESCRIPTION
**Pull request by david-inviqa**

### CODE REVIEW

**Comment by BrainCrumbz** [comment]
Not sure why CI build failed (the log seems to be empty), but one consideration is that *package.json* `main` field should be set to the library entry point path, from the perspective of a library user, so basically when the library has been build, bundled and shipped.

Not having already built the library, and judging only from repository `dist` directory, the entry point seems to be instead `my-date-picker.module.js`. Is that correct?

**Comment by kekeh** [comment]
I have already removed the **index.js** file from the build. If you are using version from the npm you can import the date picker as follows:

```javascript
// If you are using webpack package loader import the MyDatePickerModule from here:
import { MyDatePickerModule } from 'mydatepicker';

// If you are using systemjs package loader import the MyDatePickerModule from here:
import { MyDatePickerModule } from 'mydatepicker/dist/my-date-picker.module';
```

**Comment by BrainCrumbz** [comment]
Uhm ... it might be the case this issue could be reopened. Just tried with 1.1.15, importing module as stated in webpack scenario, and this is what we get:

> ERROR in ../~/mydatepicker/src/my-date-picker/my-date-picker.module.ts
Module parse failed: X:\path\to\my\project\node_modules\mydatepicker\src\my-date-picker\my-date-picker.module.ts Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
| import { InputFocusDirective } from "./directives/my-date-picker.input.directive";
|
| @NgModule({
|     imports: [CommonModule],
|     declarations: [MyDatePicker, InputFocusDirective],
 @ ../~/mydatepicker/index.ts 1:0-59
 @ ./shared/module.ts
 @ ./app/module-dev.ts
 @ ./main.browser-jit.ts

Next step is going to be trying with 1.1.16, if that can make a difference.

Apart from this specific error, the rationale behind this PR did not seem so bad, and I just wanted to share our 2c from my team. It is not a bad idea to state the main entry point within package.json for your library users.

**Comment by BrainCrumbz** [comment]
Issue confirmed with 1.1.16.

When I modify our project source code from:

```ts
import { MyDatePickerModule } from 'mydatepicker';
```

to:

```ts
import { MyDatePickerModule } from 'mydatepicker/dist/my-date-picker.module';
```

then build goes fine.

**Comment by kekeh** [comment]
Here is webpack project: https://github.com/kekeh/mydatepicker/tree/gh-pages and it imports the date picker this way: 

import { MyDatePickerModule } from 'mydatepicker';

**Comment by BrainCrumbz** [comment]
Thanks for pointing that, but I'm not 100% sure that such a demo is **really** testing the common client code scenario. Looking at its [package.json](https://github.com/kekeh/mydatepicker/blob/4ff2bc166b4cf3d170494d6ed5e01402d1593ca7/package.json) I cannot see *mydatepicker* package among dependencies. I guess it's taking that from some local copy (local *dist* folder maybe?), but that is not really testing what happens when you depend on published npm package, with webpack.

Please correct me where needed. Thanks!

**Pull request closed without merging**
