### PR TITLE
[ADD] showInput option

### PR DESCRIPTION
**Pull request by alapasset**
Need show just icon no input text

### CODE REVIEW

**Comment by alapasset** [comment]
Can you check please ?

**Comment by alapasset** [comment]
Sorry but i have forget rebuild after the changes in the last commit :) Can you rebuild to access to new build plz ?

**Comment by kekeh** [comment]
Thanks. I merged this but I changed option name to **showInputField**. You can easily test it with sampleapp.

New version of the component is: 1.1.13

**Comment by alapasset** [comment]
Thx a lot :)

**Pull request merged**
