### PR TITLE
Update my-date-picker.locale.service.ts

### PR DESCRIPTION
**Pull request by NaorSibony**
Hebrew support (not sure what the 'sunHighlight' parameter does..)

### CODE REVIEW

**Comment by kekeh** [comment]
You can verify your locale from here: http://kekeh.github.io/mydatepicker/#inlinemode

select **he** from the dropdown.

sunHighlight show sundays as red colored.

**Comment by NaorSibony** [comment]
Thanks!
Can you tell me what could be the reason for a manual year input not
working for me as in your example? Is there any flag I might be missing?

Best,
Naor S.

2017-02-13 15:27 GMT+02:00 kekeh <notifications@github.com>:

**Comment by kekeh** [comment]
In this http://kekeh.github.io/mydatepicker page both datepickers support manual year input and it works in my test.

There is option **editableMonthAndYear** which enables/disable this feature. Its default is **true**.

What is the problem?

**Comment by NaorSibony** [comment]
I am aware of this option and also to the fact that it is true by default..

1. It starts like this (ignore the absence of arrows):
[image: תמונה מוטבעת 1]
and the dom is like this:

[image: תמונה מוטבעת 3]

2. I am clicking the input field and it just vanishes

[image: תמונה מוטבעת 2]

and the dom is like this:
[image: תמונה מוטבעת 4]

2.b. Manual change of the ng-reflect-value or the input value in the dom
also doesn't do the trick.

3. Another click and it shows back.
Input of numbers while it is gone is not working.

Any idea what could it be?

Best,
Naor S.

2017-02-15 9:53 GMT+02:00 kekeh <notifications@github.com>:

**Comment by kekeh** [comment]
I don't see your images in the previous message.

**Comment by NaorSibony** [comment]
Please see attached a screenshot


2017-02-15 10:06 GMT+02:00 kekeh <notifications@github.com>:

**Comment by NaorSibony** [comment]
image

**Comment by kekeh** [comment]
Difficult to say what is the problem. What kind of environment you have in your project? What is version of Angular?

You can check this project as example: https://github.com/kekeh/mydatepicker/tree/gh-pages

The project is this application: http://kekeh.github.io/mydatepicker

**Comment by NaorSibony** [comment]
I wouldn't write to you if I didn't do it already :)

I am working with Angular 2

**Comment by kekeh** [comment]
Can you include your package.json content here? Only dependencies and devDependencies part is enough.

**Comment by NaorSibony** [comment]
"dependencies": {
    "@angular/common": "^2.3.0",
    "@angular/compiler": "^2.3.0",
    "@angular/compiler-cli": "^2.3.0",
    "@angular/core": "^2.3.0",
    "@angular/forms": "^2.3.0",
    "@angular/http": "^2.3.0",
    "@angular/platform-browser": "^2.3.0",
    "@angular/platform-browser-dynamic": "^2.3.0",
    "@angular/platform-server": "^2.3.0",
    "@angular/router": "~3.1.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.13",
    "angular-2-local-storage": "1.0.0",
    "angular2-busy": "^1.0.2",
    "angular2-fontawesome": "~0.8.0",
    "angular2-logger": "^0.5.0",
    "angular2-moment": "^1.0.0",
    "angular2localization": "^1.3.0",
    "bootstrap": "^3.3.7",
    "client-infrastructure": "git+ssh://git@git.codeoasis.com/uDigital/client-infrastructure.git#client-infrastructure-fix-bugs-css",
    "core-js": "^2.4.1",
    "font-awesome": "~4.7.0",
    "karma-jasmine": "^1.1.0",
    "moment": "^2.17.1",
    "ng2-bootstrap": "^1.1.16",
    "ng2-toasty": "^2.1.0",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.19-3",
    "codelyzer": "1.0.0-beta.1",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5"
  }

**Comment by kekeh** [comment]
In angular you have **^2.3.0** which means npm installs version **2.4.7**.
Update or add the following libraries.

    "es6-shim": "~0.35.3",
    "reflect-metadata": "0.1.9",
    "rxjs": "5.1.0",
    "zone.js": "0.7.7"

After that delete the **node_modules** folder and run **npm install**.

I have this kind of configuration and it works: https://github.com/kekeh/mydatepicker/blob/gh-pages/package.json

But I don't know what could be the problem in your environment.

**Comment by NaorSibony** [comment]
Unfortunately, that did not do the trick.
Thank you for your attempts to assist

**Comment by kekeh** [comment]
If you are still working with this datepicker can you include here your **my-date-picker** tag and its **options**?

**Comment by NaorSibony** [comment]
private myDatePickerOptions: IMyOptions = {
      // other options...
      dateFormat: 'dd/mm/yyyy',
     dayLabels: {su: "רא", mo: "שנ", tu: "של", we: "רב", th: "חמ", fr: "שי", sa: "שב"},
      monthLabels: { 1: 'ינו', 2: 'פבר', 3: 'מרץ', 4: 'אפר', 5: 'מאי', 6: 'יונ', 7: 'יול', 8: 'אוג', 9: 'ספט', 10: 'אוק', 11: 'נוב', 12: 'דצמ' },
      firstDayOfWeek: 'su',
      editableDateField: false,
      showTodayBtn: true,
      showClearDateBtn: false,
      editableMonthAndYear: true,
      sunHighlight: false,
      disableUntil: {year: new Date().getFullYear() - 60,
                      month: new Date().getMonth() + 1,
                      day: new Date().getDate()},

      disableSince: {year: new Date().getFullYear() - 21,
                    month: new Date().getMonth() + 1,
                    day: new Date().getDate()}

  };

**Comment by kekeh** [comment]
How about my-date-picker tag in HTML? Can you include it also?

**Comment by NaorSibony** [comment]
Sorry for the delay

Here is my piece of html code:

<my-date-picker [options]="myDatePickerOptions"
                      (dateChanged)="onDateChanged($event)"></my-date-picker>


No initial date setting is required for me

**Comment by kekeh** [comment]
You can remove the dayLabels, monthLabels, dateFormat, firstDayOfWeek, todayBtnTxt and sunHighlight from the options because we added **he** locale to date picker. You can use that locale as follows:

```html
<my-date-picker [options]="myDatePickerOptions" [locale]="locale"
                    (dateChanged)="onDateChanged($event)" ></my-date-picker>
```

```javascript
private locale: string = 'he';
```

**Pull request merged**
